In [1]:
import pandas as pd

ruta_archivo_json = 'C:\\Users\\ROXI\\OneDrive\\Escritorio\\henry\\pi\\PI01_DATA03\\Datasets\\drivers.json'
datos = pd.read_json(ruta_archivo_json,  lines=True, encoding="utf-8")
datos

,driverId,driverRef,number,code,name,dob,nationality,url
0,1,hamilton,44,HAM,"{'forename': 'Lewis', 'surname': 'Hamilton'}",1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,"{'forename': 'Nick', 'surname': 'Heidfeld'}",1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,"{'forename': 'Nico', 'surname': 'Rosberg'}",1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,"{'forename': 'Fernando', 'surname': 'Alonso'}",1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,"{'forename': 'Heikki', 'surname': 'Kovalainen'}",1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...
848,850,pietro_fittipaldi,51,FIT,"{'forename': 'Pietro', 'surname': 'Fittipaldi'}",1996-06-25,Brazilian,http://en.wikipedia.org/wiki/Pietro_Fittipaldi
849,851,aitken,89,AIT,"{'forename': 'Jack', 'surname': 'Aitken'}",1995-09-23,British,http://en.wikipedia.org/wiki/Jack_Aitken
850,852,tsunoda,\N,TSU,"{'forename': 'Yuki', 'surname': 'Tsunoda'}",2000-05-11,Japanese,http://en.wikipedia.org/wiki/Yuki_Tsunoda
851,853,mazepin,\N,MAZ,"{'forename': 'Nikita', 'surname': 'Mazepin'}",1999-03-02,Russian,http://en.wikipedia.org/wiki/Nikita_Mazepin
852,854,mick_schumacher,\N,SCH,"{'forename': 'Mick', 'surname': 'Schumacher'}",1999-03-22,German,http://en.wikipedia.org/wiki/Mick_Schumacher

In [495]:

datos_dict=datos['name'].to_dict()

In [496]:
datos[["forename","surname"]]=pd.DataFrame.from_dict(datos_dict,orient='index')

In [501]:
datos.to_csv('drivers_.csv', encoding='utf-8', index=False)

In [504]:
datos_df1=pd.read_csv(r'C:\Users\ROXI\OneDrive\Escritorio\Proyecto Individual 1- Data 03- Soy Henry\Proyecto-Individual-1\Datasets\pandas\dataset_procesados\drivers_.csv')

In [460]:
datos.drop(columns="name")

,driverId,driverRef,number,code,dob,nationality,url,forename,surname
0,1,hamilton,44,HAM,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,Lewis,Hamilton
1,2,heidfeld,\N,HEI,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld,Nick,Heidfeld
2,3,rosberg,6,ROS,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg,Nico,Rosberg
3,4,alonso,14,ALO,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso,Fernando,Alonso
4,5,kovalainen,\N,KOV,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen,Heikki,Kovalainen
...,...,...,...,...,...,...,...,...,...
848,850,pietro_fittipaldi,51,FIT,1996-06-25,Brazilian,http://en.wikipedia.org/wiki/Pietro_Fittipaldi,Pietro,Fittipaldi
849,851,aitken,89,AIT,1995-09-23,British,http://en.wikipedia.org/wiki/Jack_Aitken,Jack,Aitken
850,852,tsunoda,\N,TSU,2000-05-11,Japanese,http://en.wikipedia.org/wiki/Yuki_Tsunoda,Yuki,Tsunoda
851,853,mazepin,\N,MAZ,1999-03-02,Russian,http://en.wikipedia.org/wiki/Nikita_Mazepin,Nikita,Mazepin
852,854,mick_schumacher,\N,SCH,1999-03-22,German,http://en.wikipedia.org/wiki/Mick_Schumacher,Mick,Schumacher

In [505]:
datos=datos.drop(columns="name")

In [506]:
datos

,driverId,driverRef,number,code,dob,nationality,url,forename,surname
0,1,hamilton,44,HAM,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,Lewis,Hamilton
1,2,heidfeld,\N,HEI,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld,Nick,Heidfeld
2,3,rosberg,6,ROS,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg,Nico,Rosberg
3,4,alonso,14,ALO,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso,Fernando,Alonso
4,5,kovalainen,\N,KOV,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen,Heikki,Kovalainen
...,...,...,...,...,...,...,...,...,...
848,850,pietro_fittipaldi,51,FIT,1996-06-25,Brazilian,http://en.wikipedia.org/wiki/Pietro_Fittipaldi,Pietro,Fittipaldi
849,851,aitken,89,AIT,1995-09-23,British,http://en.wikipedia.org/wiki/Jack_Aitken,Jack,Aitken
850,852,tsunoda,\N,TSU,2000-05-11,Japanese,http://en.wikipedia.org/wiki/Yuki_Tsunoda,Yuki,Tsunoda
851,853,mazepin,\N,MAZ,1999-03-02,Russian,http://en.wikipedia.org/wiki/Nikita_Mazepin,Nikita,Mazepin
852,854,mick_schumacher,\N,SCH,1999-03-22,German,http://en.wikipedia.org/wiki/Mick_Schumacher,Mick,Schumacher

In [507]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 853 entries, 0 to 852
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     853 non-null    int64
 1   driverRef    853 non-null    object
 2   number       853 non-null    object
 3   code         853 non-null    object
 4   dob          853 non-null    object
 5   nationality  853 non-null    object
 6   url          853 non-null    object
 7   forename     853 non-null    object
 8   surname      853 non-null    object
dtypes: int64(1), object(8)
memory usage: 60.1+ KB

In [2]:
datos[datos['driverId'] == 18]

,driverId,driverRef,number,code,name,dob,nationality,url
17,18,button,22,BUT,"{'forename': 'Jenson', 'surname': 'Button'}",1980-01-19,British,http://en.wikipedia.org/wiki/Jenson_Button

In [508]:
#convert to lower case
datos['driverRef'] = datos['driverRef'].str.lower()
# remove trailing white spaces
datos['driverRef'] = datos['driverRef'].str.strip()

In [509]:
sort_values=datos['driverRef'].sort_values()
sort_values.unique()

array(['abate', 'abecassis', 'acheson', 'adamich', 'adams', 'ader',
       'adolff', 'agabashian', 'ahrens', 'aitken', 'alan_brown', 'albers',
       'albon', 'alboreto', 'alesi', 'alguersuari', 'alliot', 'allison',
       'alonso', 'amati', 'ambrosio', 'amick', 'amon', 'anderson',
       'andersson', 'andre_pilette', 'andretti', 'andrews', 'angelis',
       'apicella', 'armi', 'arnold', 'arnoux', 'arundell', 'ascari',
       'ashdown', 'ashley', 'ashmore', 'aston', 'attwood', 'ayulo',
       'badoer', 'baghetti', 'bailey', 'baldi', 'ball', 'balsa',
       'bandini', 'banks', 'barbazza', 'barber', 'barilla', 'barrichello',
       'bartels', 'barth', 'bassi', 'bauer', 'baumgartner', 'bayol',
       'beaufort', 'beauman', 'bechem', 'behra', 'bell', 'bellof',
       'belmondo', 'belso', 'beltoise', 'beretta', 'berg', 'berger',
       'bernard', 'bernoldi', 'bertaggia', 'bettenhausen', 'beuttler',
       'bianchi', 'bianco', 'bill_moss', 'binder', 'biondetti', 'bira',
       'birger', 'bisch', 'blanchard', 'bleekemolen', 'blignaut',
       'blokdyk', 'blundell', 'bob_scott', 'boesel', 'boffa', 'bondurant',
       'bonetto', 'bonnier', 'bonomi', 'bordeu', 'borgudd', 'botha',
       'bottas', 'boullion', 'bourdais', 'boutsen', 'boyd', 'brabham',
       'brack', 'brambilla', 'branca', 'brancatelli', 'brandon',
       'branson', 'brendon_hartley', 'bridger', 'brise', 'bristow',
       'broeker', 'brooks', 'brown', 'brudes', 'brundle', 'bruni',
       'bruno_senna', 'bryan', 'bucci', 'bucknum', 'bueb', 'buemi',
       'bueno', 'burgess', 'burti', 'bussinello', 'button', 'byrne',
       'cabantous', 'cabianca', 'cabral', 'cade', 'caffi',
       'campbell-jones', 'campos', 'cannoc', 'cantoni', 'cantrell',
       'capelli', 'carini', 'castellotti', 'cecotto', 'cesaris', 'cevert',
       'chaboud', 'chamberlain', 'chandhok', 'changy', 'chapman',
       'charlton', 'charrington', 'chaves', 'cheesbourg', 'cheever',
       'chiesa', 'chilton', 'chimeri', 'chiron', 'chitwood', 'christie',
       'claes', 'clapham', 'clark', 'cogan', 'collins', 'collomb',
       'colombo', 'comas', 'comotti', 'connor', 'constantine', 'cordts',
       'corrado_fabi', 'coulthard', 'courage', 'craft', 'crawford',
       'crespo', 'creus', 'crockett', 'crook', 'cross', 'crossley',
       'cruz', 'daigh', 'dalmas', 'daly', 'damon_hill', 'danner',
       'daponte', 'darter', 'davidson', 'davies', 'davis', 'daywalt',
       'deletraz', 'dempsey_wilson', 'dennis_taylor', 'depailler',
       'desire_wilson', 'dick_rathmann', 'diniz', 'dinsmore', 'dochnal',
       'dolhem', 'donnelly', 'donohue', 'doornbos', 'downing', 'drake',
       'driver', 'drogo', 'dryver', 'duke', 'dumfries', 'duncan',
       'duncan_hamilton', 'dusio', 'eaton', 'ecclestone', 'edmunds',
       'edwards', 'elford', 'elisian', 'emerson_fittipaldi', 'emery',
       'enge', 'england', 'ericsson', 'ernesto_brambilla', 'ertl',
       'estefano', 'etancelin', 'evans', 'fabi', 'fabre', 'facetti',
       'fagioli', 'fairman', 'fangio', 'farina', 'faulkner', 'filippis',
       'firman', 'fischer', 'fisher', 'fisichella', 'fitch', 'fittipaldi',
       'fitzau', 'flaherty', 'flinterman', 'flockhart', 'fohr', 'foitek',
       'follmer', 'fonder', 'fontana', 'fontes', 'forberg', 'force',
       'forini', 'foyt', 'francia', 'freeland', 'frentzen', 'frere',
       'friesacher', 'fry', 'fushida', 'gabbiani', 'gachot', 'gaillard',
       'galica', 'galli', 'galvez', 'gamble', 'ganley', 'garde',
       'gardner', 'garrett', 'gartner', 'gary_brabham', 'gasly', 'gavin',
       'gaze', 'geki', 'gendebien', 'gene', 'george', 'george_amick',
       'george_connor', 'georges_berger', 'gerard', 'gerini', 'gethin',
       'ghinzani', 'giacomelli', 'gibson', 'gilles_villeneuve', 'gimax',
       'ginther', 'giovinazzi', 'giunti', 'glock', 'godia', 'goethals',
       'goldsmith', 'gonzalez', 'gordini', 'gould', 'gounon',
       'graffenried', 'graham_whitehead', 'grassi', 'green', 'greene',
       'gregory', 'griffith', 'grignard', 'grim', 'grosjean',
       'grouillard', 'gubby', 'guelfi', 'guerra', 'guerrero', 'gugelmin',
       'gurney', 'gutierrez', 'guy_mairesse', 'hahne', 'hailwood',
       'hakkinen', 'halford', 'hall', 'hamilton', 'hampshire', 'hanks',
       'hans_stuck', 'hansgen', 'harris', 'harrison', 'hart', 'hartley',
       'haryanto', 'hasemi', 'hattori', 'hawkins', 'hawthorn', 'hayje',
       'heeks', 'heidfeld', 'helfrich', 'hellings', 'henry_taylor',
       'henton', 'herbert', 'herman', 'herrmann', 'hesnault', 'heyer',
       'hill', 'hirt', 'hobbs', 'hocking', 'hoffmann', 'holland',
       'holmes', 'homeier', 'hoshino', 'hoyt', 'hulkenberg', 'hulme',
       'hunt', 'hurtubise', 'hutchison', 'ian_scheckter', 'ian_stewart',
       'ickx', 'ide', 'iglesias', 'inoue', 'ireland', 'irvine', 'irwin',
       'jabouille', 'jack_brabham', 'jackson', 'james', 'jarier', 'jean',
       'jerry_unser', 'jimmy_stewart', 'jo_schlesser',
       'joachim_winkelhock', 'johansson', 'john_barber', 'john_james',
       'johnson', 'johnstone', 'jolyon_palmer', 'jones', 'jover',
       'jules_bianchi', 'karch', 'karthikeyan', 'katayama', 'kavanagh',
       'keegan', 'keizan', 'keke_rosberg', 'keller', 'kelly', 'ken_miles',
       'kennedy', 'kessel', 'kessler', 'kevin_magnussen', 'kiesa',
       'kinnunen', 'kladis', 'klenk', 'klerk', 'klien', 'kling',
       'klodwig', 'kobayashi', 'koinigg', 'kovalainen', 'kozarowitzky',
       'krause', 'kubica', 'kuhnke', 'kvyat', 'la_caze', 'laffite',
       'lagorce', 'lammers', 'lamy', 'landi', 'lang', 'langes', 'larini',
       'larrauri', 'larreta', 'larrousse', 'larson', 'latifi', 'lauda',
       'laurent', 'lavaggi', 'lawrence', 'leclerc', 'leclere', 'lederle',
       'lees', 'legat', 'lehto', 'lennep', 'leoni', 'leslie_johnson',
       'leston', 'levegh', 'levrett', 'lewis', 'lewis-evans', 'ligier',
       'linden', 'lippi', 'liuzzi', 'lof', 'lombardi', 'londono', 'loof',
       'lotterer', 'louveau', 'love', 'lovely', 'loyer', 'lucas',
       'lucienbonnet', 'lunger', 'macdowel', 'mackay-fraser', 'mackey',
       'macklin', 'magee', 'maggs', 'magill', 'maglioli', 'magnussen',
       'mairesse', 'maldonado', 'manfred_winkelhock', 'mansell',
       'mantovani', 'mantz', 'manzon', 'marimon', 'mario_andretti',
       'marko', 'markus_winkelhock', 'marques', 'marr', 'marsh', 'martin',
       'martini', 'mass', 'massa', 'matta', 'max_verstappen', 'may',
       'mayer', 'mazepin', 'mazet', 'mazzacane', 'mcalpine', 'mccarthy',
       'mccoy', 'mcdowell', 'mcgrath', 'mcguire', 'mclaren', 'mcnish',
       'mcrae', 'mcwithey', 'menditeguy', 'merhi', 'merzario',
       'michael_schumacher', 'mick_schumacher', 'mieres', 'migault',
       'mike_taylor', 'miles', 'milhoux', 'miller', 'mitter', 'modena',
       'monarch', 'montagny', 'monteiro', 'montermini', 'monteverdi',
       'montoya', 'morbidelli', 'moreno', 'morgan', 'moser', 'moss',
       'munaron', 'murray', 'musso', 'nakajima', 'nakano', 'nalon',
       'nannini', 'naspetti', 'nasr', 'natili', 'naylor', 'nazaruk',
       'needell', 'nelleman', 'neve', 'nicholson', 'niday', 'niedermayr',
       'niemann', 'nilsson', 'noda', 'norris', 'nuckey', 'obrien', 'ocon',
       'oliver', 'ongais', 'opel', 'orey', 'oscar_gonzalez', 'owen',
       'pace', 'pagani', 'paletti', 'palm', 'palmer', 'panis', 'pantano',
       'papis', 'parker', 'parkes', 'parnell', 'parsons', 'patrese',
       'paul_russo', 'pease', 'penske', 'perdisa', 'perez', 'perkins',
       'pescarolo', 'pesenti_rossi', 'peter_walker', 'peters', 'peterson',
       'petrov', 'phil_hill', 'pian', 'pic', 'picard', 'pieterse',
       'pietro_fittipaldi', 'pietsch', 'pilette', 'piotti', 'piper',
       'piquet', 'piquet_jr', 'pirocchi', 'pironi', 'pirro', 'pizzonia',
       'poele', 'pollet', 'pon', 'poore', 'portago', 'posey', 'pozzi',
       'pretorius', 'prinoth', 'prophet', 'prost', 'pryce', 'purley',
       'puzey', 'quester', 'raby', 'rahal', 'raikkonen',
       'ralf_schumacher', 'ramos', 'raphanel', 'rathmann', 'ratzenberger',
       'ray_crawford', 'rebaque', 'redman', 'reece', 'reed', 'rees',
       'reg_parnell', 'regazzoni', 'resta', 'reutemann', 'reventlow',
       'revson', 'rhodes', 'ribeiro', 'ricardo_rodriguez', 'ricciardo',
       'richardson', 'riess', 'rigsby', 'rindt', 'riseley_prichard',
       'riu', 'robarts', 'rodriguez', 'roig', 'rol', 'rollinson', 'rolt',
       'roos', 'rooyen', 'rosa', 'rosberg', 'rose', 'rosier', 'rosset',
       'rossi', 'rothengatter', 'ruby', 'russell', 'russo', 'ruttman',
       'ryan', 'sachs', 'said', 'sainz', 'sala', 'salazar', 'salo',
       'salvadori', 'sanesi', 'sarrazin', 'sato', 'satoru_nakajima',
       'scarborough', 'scarfiotti', 'scarlatti', 'scheckter', 'schell',
       'schenken', 'scherrer', 'schiattarella', 'schiller', 'schindler',
       'schlesser', 'schneider', 'schoeller', 'schroeder', 'schuppan',
       'scott_brown', 'scotti', 'seidel', 'seiffert', 'senna', 'serafini',
       'serra', 'serrurier', 'settember', 'sharp', 'shawe_taylor',
       'shelby', 'shelly', 'siffert', 'simon', 'sirotkin', 'slotemaker',
       'solana', 'sommer', 'sospiri', 'south', 'sparken', 'speed',
       'spence', 'stacey', 'starrabba', 'stevens', 'stevenson', 'stewart',
       'stohr', 'stommelen', 'streiff', 'stroll', 'stuck', 'stuppacher',
       'sullivan', 'surer', 'surtees', 'sutcliffe', 'sutil', 'sutton',
       'suzuki', 'swaters', 'sweikert', 'takagi', 'takahara', 'takahashi',
       'tambay', 'taramazzo', 'tarquini', 'taruffi', 'taylor', 'teague',
       'templeman', 'terra', 'testut', 'thackwell', 'thiele', 'thompson',
       'thomson', 'thorne', 'tingelstad', 'tingle', 'titterington',
       'tolan', 'tom_jones', 'tomaso', 'tornaco', 'toshio_suzuki',
       'trevor_taylor', 'trimmer', 'trintignant', 'trips', 'trulli',
       'tsunoda', 'tuero', 'tunmer', 'turner', 'ulmen', 'unser', 'uria',
       'vaccarella', 'vandoorne', 'veith', 'vergne', 'verstappen',
       'vettel', 'vic_wilson', 'villeneuve', 'villeneuve_sr', 'villoresi',
       'villota', 'volonterio', 'vonlanthen', 'vos', 'vukovich', 'vyver',
       'wacker', 'walker', 'wallard', 'walt_brown', 'walter', 'ward',
       'warwick', 'watson', 'webb', 'webber', 'wehrlein', 'weidler',
       'weiler', 'wendlinger', 'westbury', 'weyant', 'wharton',
       'whiteaway', 'whitehead', 'whitehouse', 'widdows', 'wietzes',
       'wilds', 'williams', 'williamson', 'wilson', 'wilson_fittipaldi',
       'wisell', 'wunderink', 'wurz', 'yamamoto', 'yoong', 'zanardi',
       'zapico', 'zonta', 'zorzi', 'zunino'], dtype=object)

In [510]:
#convert to lower case
datos['code'] = datos['code'].str.lower()
# remove trailing white spaces
datos['code'] = datos['code'].str.strip()

In [511]:
sort_code=datos['code'].sort_values()
sort_code.unique()

array(['\\n', 'ait', 'alb', 'alg', 'alo', 'bad', 'bar', 'bia', 'bot',
       'bou', 'bue', 'but', 'cha', 'chi', 'cou', 'dam', 'dav', 'dig',
       'dir', 'dlr', 'doo', 'eri', 'fis', 'fit', 'fmo', 'fri', 'gas',
       'gio', 'glo', 'gro', 'gut', 'ham', 'har', 'hei', 'hul', 'ide',
       'kar', 'kli', 'kob', 'kov', 'kub', 'kvy', 'lat', 'lec', 'liu',
       'lot', 'mag', 'mal', 'mas', 'maz', 'mer', 'mon', 'msc', 'nak',
       'nas', 'nor', 'oco', 'pal', 'per', 'pet', 'pic', 'piq', 'piz',
       'rai', 'ric', 'ros', 'rss', 'rus', 'sai', 'sat', 'sch', 'sen',
       'sir', 'spe', 'ste', 'str', 'sut', 'tmo', 'tru', 'tsu', 'van',
       'vdg', 'ver', 'vet', 'vil', 'web', 'weh', 'win', 'wur', 'yam',
       'zon'], dtype=object)

In [512]:
#convert to lower case
datos['nationality'] = datos['nationality'].str.lower()
# remove trailing white spaces
datos['nationality'] = datos['nationality'].str.strip()

In [513]:
sort_nationality=datos['nationality'].sort_values()
sort_nationality.unique()

array(['american', 'american-italian', 'argentine', 'argentine-italian',
       'australian', 'austrian', 'belgian', 'brazilian', 'british',
       'canadian', 'chilean', 'colombian', 'czech', 'danish', 'dutch',
       'east german', 'finnish', 'french', 'german', 'hungarian',
       'indian', 'indonesian', 'irish', 'italian', 'japanese',
       'liechtensteiner', 'malaysian', 'mexican', 'monegasque',
       'new zealander', 'polish', 'portuguese', 'rhodesian', 'russian',
       'south african', 'spanish', 'swedish', 'swiss', 'thai',
       'uruguayan', 'venezuelan'], dtype=object)

In [514]:
#convert to lower case
datos['forename'] = datos['forename'].str.lower()
# remove trailing white spaces
datos['forename'] = datos['forename'].str.strip()

In [515]:
sort_forename=datos['forename'].sort_values(ascending=False)
sort_forename.unique()

array(['Ã³scar', 'Ã©rik', 'Ã©ric', 'Ã©lie', 'zsolt', 'yves', 'yuki', 'yuji',
       'yannick', 'wolfgang', 'wilson', 'willy', 'willi', 'will', 'wayne',
       'warwick', 'walt', 'volker', 'vittorio', 'vitantonio', 'vitaly',
       'vincenzo', 'vic', 'vern', 'valtteri', 'umberto', 'ukyo', 'troy',
       'trevor', 'travis', 'toulo', 'toshio', 'torsten', 'toranosuke',
       'tony', 'toni', 'tomÃ¡Å¡', 'tommy', 'tom', 'timo', 'timmy', 'tim',
       'tiff', 'tiago', 'thomas', 'thierry', 'theo', 'teo', 'teddy',
       'ted', 'tarso', 'takuma', 'taki', 'sÃ©bastien', 'syd', 'stÃ©phane',
       'stuart', 'stoffel', 'stirling', 'stephen', 'stefano', 'stefan',
       'slim', 'skip', 'silvio', 'siegfried', 'shorty', 'shinji',
       'sergio', 'sergey', 'sebastian', 'scott', 'satoru', 'sam', 'sakon',
       'rupert', 'rudolf', 'rudi', 'rubens', 'roy', 'ronnie', 'ron',
       'romain', 'rolf', 'roland', 'roger', 'roelof', 'rodney', 'rodger',
       'robin', 'roberto', 'robert', 'rob', 'rio', 'rikky', 'richie',
       'richard', 'riccardo', 'ricardo', 'renÃ©', 'renzo', 'renato',
       'reine', 'reg', 'red', 'raymond', 'ray', 'raul', 'ralph', 'ralf',
       'prince', 'pietro', 'piers', 'pierre-henri', 'pierre', 'piero',
       'pierluigi', 'piercarlo', 'philippe', 'philip', 'phil', 'peter',
       'pete', 'perry', 'pedro', 'paul', 'patrick', 'pat', 'pastor',
       'pascal', 'paolo', 'paddy', 'paco', 'pablo', 'ottorino', 'otto',
       'oswald', 'oscar', 'onofre', 'olivier', 'noritake', 'norberto',
       'nino', 'nikita', 'niki', 'nigel', 'nicolas', 'nicola', 'nico',
       'nick', 'nicholas', 'neville', 'nelson', 'nello', 'nasif',
       'narain', 'naoki', 'nanni', 'mÃ¡rio de araÃºjo', 'myron', 'moisÃ©s',
       'mikko', 'mike', 'mika', 'miguel Ã¡ngel', 'mick', 'michele',
       'michel', 'michael', 'menato', 'max', 'maurÃ­cio', 'mauro',
       'maurice', 'mauri', 'masten', 'massimo', 'massimiliano',
       'masahiro', 'martin', 'marshall', 'markus', 'mark', 'mario',
       'maria', 'marcus', 'marco', 'marcel', 'marc', 'manny', 'manfred',
       'mack', 'luki', 'luiz', 'luis', 'luigi', 'ludovico', 'lucien',
       'luciano', 'lucas', 'luca', 'louis', 'loris', 'lorenzo', 'lloyd',
       'lewis', 'leslie', 'les', 'leo', 'len', 'lella', 'lee', 'larry',
       'lando', 'lance', 'lamberto', 'kurt', 'kunimitsu', 'kimi', 'kevin',
       'kenny', 'kenneth', 'ken', 'keke', 'keith', 'kazuyoshi', 'kazuki',
       'karun', 'karl', 'kamui', 'jÃ©rÃ´me', 'jyrki', 'justin', 'julian',
       'jules', 'jud', 'juan manuel', 'juan', 'josÃ© froilÃ¡n', 'josÃ©',
       'josef', 'jos', 'jorge', 'jonathan', 'jolyon', 'joie', 'johnny',
       'johnnie', 'john', 'joe', 'jody', 'jochen', 'joachim', 'jo',
       'jimmy', 'jim', 'jesÃºs', 'jerry', 'jenson', 'jean-Ã©ric',
       'jean-pierre', 'jean-marc', 'jean-louis', 'jean-denis',
       'jean-christophe', 'jean', 'jay', 'jarno', 'jan', 'james', 'jaime',
       'jacques', 'jacky', 'jackie', 'jack', 'jac', 'ivor', 'ivan',
       'innes', 'ingo', 'ignazio', 'ian', 'huub', 'hubert', 'howden',
       'horace', 'hiroshi', 'hideki', 'hernando', 'hermann', 'herbert',
       'henry', 'henri', 'helmuth', 'helmut', 'heinz-harald', 'heinz',
       'heini', 'heikki', 'hector', 'harry', 'harald', 'hap',
       'hans-joachim', 'hans', 'gÃ¼nther', 'gÃ©rard', 'guy', 'gus',
       'gunnar', 'gregor', 'graham', 'giulio', 'giovanni', 'giovanna',
       'giorgio', 'gino', 'gilles', 'gijs', 'giedo', 'gianni',
       'gianmaria', 'gianfranco', 'giancarlo', 'giacomo', 'gerry',
       'gerino', 'gerhard', 'georges', 'george', 'geoff', 'gene',
       'gastÃ³n', 'gary', 'gaetano', 'gabriele', 'fritz', 'fred',
       'franÃ§ois', 'frank', 'franco', 'franck', 'fernando', 'felipe',
       'felice', 'fabrizio', 'eugÃ¨ne', 'eugenio', 'ettore', 'esteban',
       'erwin', 'ernst', 'ernie', 'ernesto', 'eric', 'eppie', 'enrique',
       'enrico', 'emilio', 'emerson', 'emanuele', 'elmer', 'eliseo',
       'elio', 'eitel', 'edgar', 'eddie', 'ed', 'duncan', 'duke', 'duane',
       'dries', 'doug', 'dorino', 'don', 'domenico', 'divina', 'dieter',
       'didier', 'dick', 'desmond', 'desirÃ©', 'derek', 'denny', 'dennis',
       'dempsey', 'david', 'dave', 'danny', 'daniil', 'daniel', 'dan',
       'damon', 'damien', 'cuth', 'cristiano', 'corrado', 'consalvo',
       'conny', 'colin', 'clive', 'cliff', 'clemente', 'clemar', 'clay',
       'claudio', 'chuck', 'christijan', 'christian', 'chris', 'chico',
       'chet', 'charles', 'cesare', 'cecil', 'carroll', 'carlos', 'carlo',
       'carl', 'carel godin', 'cal', 'bud', 'bruno', 'bruce', 'brian',
       'brett', 'brendon', 'brausch', 'boy', 'bobby', 'bob', 'billy',
       'bill', 'bertrand', 'bertil', 'bernie', 'bernd', 'bernard',
       'beppe', 'ben', 'bayliss', 'basil', 'azdrubal', 'ayrton', 'arturo',
       'arthur', 'art', 'archie', 'antÃ´nio', 'antonio', 'anthony', 'andy',
       'andrÃ©', 'andrea', 'allen', 'allan', 'alfredo', 'alfonso',
       'alexander', 'alex', 'alessandro', 'aldo', 'alberto rodriguez',
       'alberto', 'albert', 'alan', 'alain', 'al', 'aguri', 'adriÃ¡n',
       'adrian', 'adolfo', 'adolf'], dtype=object)

In [516]:
rep = {'Ã£':'a','Ã¡':'a','Ã©':'e','Ã­':'i','Ã³':'o','Ã´':'o','Ãº':'u','`a':'a','Ã¨':'e','Ã¬':'i','Ã²':'o','Ã¹':'u','Ã§':'c','Ã±':'n','Å¡':'s','Ã¸':''}

datos['forename'] =datos['forename'].replace(rep, regex=True)

In [517]:
import unicodedata 
def remove_accents(input_str):
    nkfd_form = unicodedata.normalize('NFKD', input_str) 
    only_ascii = nkfd_form.encode('ASCII', 'ignore') 
    only_ascii
    
    return only_ascii

In [518]:
# Apply to your df
datos_decode= datos["forename"].apply(remove_accents)

In [519]:

datos["forename"]=datos_decode.str.decode('utf8', errors='strict')

In [520]:
#convert to lower case
datos['surname'] = datos['surname'].str.lower()
# remove trailing white spaces
datos['surname'] = datos['surname'].str.strip()

In [521]:
sort_forename=datos['surname'].sort_values()
sort_forename.unique()

array(['abate', 'abecassis', 'acheson', 'adams', 'ader', 'adolff',
       'agabashian', 'ahrens', 'aitken', 'albers', 'albon', 'alboreto',
       'alesi', 'alguersuari', 'alliot', 'allison', 'alonso', 'amati',
       'amick', 'amon', 'anderson', 'andersson', 'andretti', 'andrews',
       'apicella', 'armi', 'arnold', 'arnoux', 'arundell', 'ascari',
       'ashdown', 'ashley', 'ashmore', 'aston', 'attwood', 'ayulo',
       'badoer', 'baghetti', 'bailey', 'baldi', 'ball', 'balsa',
       'bandini', 'banks', 'barbazza', 'barber', 'barilla', 'barrichello',
       'bartels', 'barth', 'bassi', 'bauer', 'baumgartner', 'bayol',
       'beauman', 'bechem', 'behra', 'bell', 'bellof', 'belmondo',
       'belsÃ¸', 'beltoise', 'beretta', 'berg', 'berger', 'bernard',
       'bernoldi', 'bertaggia', 'bettenhausen', 'beuttler', 'bianchi',
       'bianco', 'binder', 'biondetti', 'bira', 'birger', 'bisch',
       'blanchard', 'bleekemolen', 'blignaut', 'blokdyk', 'blundell',
       'boesel', 'boffa', 'bondurant', 'bonetto', 'bonnier', 'bonomi',
       'bordeu', 'borgudd', 'botha', 'bottas', 'boullion', 'bourdais',
       'boutsen', 'boyd', 'brabham', 'brack', 'brambilla', 'branca',
       'brancatelli', 'brandon', 'branson', 'bridger', 'brise', 'bristow',
       'broeker', 'brooks', 'brown', 'brudes', 'brundle', 'bruni',
       'bryan', 'bucci', 'bucknum', 'bueb', 'buemi', 'bueno', 'burgess',
       'burti', 'bussinello', 'button', 'byrne', 'cabantous', 'cabianca',
       'cabral', 'cade', 'caffi', 'campbell-jones', 'campos', 'cannon',
       'cantoni', 'cantrell', 'capelli', 'carini', 'carter',
       'castellotti', 'cecotto', 'cevert', 'chaboud', 'chamberlain',
       'chandhok', 'chapman', 'charlton', 'chaves', 'cheesbourg',
       'cheever', 'chiesa', 'chilton', 'chimeri', 'chiron', 'chitwood',
       'christie', 'claes', 'clapham', 'clark', 'cogan', 'collins',
       'collomb', 'colombo', 'comas', 'comotti', 'connor', 'constantine',
       'cordts', 'coulthard', 'courage', 'craft', 'crawford', 'crespo',
       'creus', 'crockett', 'crook', 'cross', 'crossley', 'cruz',
       "d'ambrosio", "d'orey", 'da matta', 'da silva ramos', 'daigh',
       'dalmas', 'daly', 'danner', 'daponte', 'davidson', 'davies',
       'davis', 'daywalt', 'de adamich', 'de angelis', 'de beaufort',
       'de cesaris', 'de changy', 'de dryver', 'de filippis',
       'de graffenried', 'de klerk', 'de la rosa', 'de portago', 'de riu',
       'de terra', 'de tomaso', 'de tornaco', 'de villota', 'de vos',
       'depailler', 'di grassi', 'di resta', 'diniz', 'dinsmore',
       'dochnal', 'dolhem', 'donnelly', 'donohue', 'doornbos', 'downing',
       'drake', 'driver', 'drogo', 'duke', 'dumfries', 'duncan', 'dusio',
       'dÃ©lÃ©traz', 'eaton', 'ecclestone', 'edmunds', 'edwards', 'elford',
       'elisian', 'emery', 'enge', 'england', 'ericsson', 'ertl',
       'estÃ©fano', 'evans', 'fabi', 'fabre', 'facetti', 'fagioli',
       'fairman', 'fangio', 'farina', 'faulkner', 'firman', 'fischer',
       'fisher', 'fisichella', 'fitch', 'fittipaldi', 'fitzau',
       'flaherty', 'flinterman', 'flockhart', 'fohr', 'foitek', 'follmer',
       'fonder', 'fontana', 'fontes', 'forberg', 'force', 'forini',
       'fotheringham-parker', 'foyt', 'franchi', 'francia', 'freeland',
       'frentzen', 'friesacher', 'fry', 'frÃ¨re', 'fushida', 'gabbiani',
       'gachot', 'gaillard', 'galica', 'galli', 'gamble', 'ganley',
       'gardner', 'garrett', 'gartner', 'gasly', 'gaze', 'gendebien',
       'genÃ©', 'george', 'gerard', 'gerini', 'gethin', 'ghinzani',
       'giacomelli', 'gibson', 'ginther', 'giovinazzi', 'giunti', 'glock',
       'godia', 'goethals', 'goldsmith', 'gonzÃ¡lez', 'gordini', 'gould',
       'gounon', 'green', 'greene', 'gregory', 'griffith', 'grignard',
       'grim', 'grosjean', 'grouillard', 'gubby', 'guelfi', 'guerra',
       'guerrero', 'gugelmin', 'gurney', 'gutiÃ©rrez', 'gÃ¡lvez', 'hahne',
       'hailwood', 'halford', 'hall', 'hamilton', 'hampshire', 'hanks',
       'hansgen', 'harris', 'harrison', 'hart', 'hartley', 'haryanto',
       'hasemi', 'hattori', 'hawkins', 'hawthorn', 'heeks', 'heidfeld',
       'helfrich', 'hellings', 'henton', 'herbert', 'herman', 'herrmann',
       'hesnault', 'heyer', 'hill', 'hirt', 'hobbs', 'hocking',
       'hoffmann', 'holland', 'holmes', 'homeier', 'hoshino', 'hoyt',
       'hulme', 'hunt', 'hurtubise', 'hutchison', 'hÃ¤kkinen',
       'hÃ¼lkenberg', 'ickx', 'ide', 'iglesias', 'inoue', 'ireland',
       'irvine', 'irwin', 'jabouille', 'jackson', 'james', 'jarier',
       'jean', 'johansson', 'johnson', 'johnstone', 'jones', 'jover',
       'jÃ¤rvilehto', 'karch', 'karthikeyan', 'katayama', 'kavanagh',
       'keegan', 'keizan', 'keller', 'kelly', 'kennedy', 'kessel',
       'kessler', 'kiesa', 'kinnunen', 'kladis', 'klenk', 'klien',
       'kling', 'klodwig', 'kobayashi', 'koinigg', 'kovalainen',
       'kozarowitzky', 'krause', 'kubica', 'kuhnke', 'kvyat', 'la caze',
       'laffite', 'lagorce', 'lammers', 'lamy', 'landi', 'lang', 'langes',
       'larini', 'larrauri', 'larreta', 'larrousse', 'larson', 'latifi',
       'lauda', 'laurent', 'lavaggi', 'lawrence', 'leclerc', 'leclÃ¨re',
       'lederle', 'lees', 'legat', 'leoni', 'leston', 'levegh', 'levrett',
       'lewis', 'lewis-evans', 'ligier', 'linden', 'lippi', 'liuzzi',
       'lombardi', 'londoÃ±o', 'loof', 'lotterer', 'louveau', 'love',
       'lovely', 'loyer', 'lucas', 'lucienbonnet', 'lunger', 'macdowel',
       'mackay-fraser', 'mackey', 'macklin', 'magee', 'maggs', 'magill',
       'maglioli', 'magnussen', 'mairesse', 'maldonado', 'mansell',
       'mantovani', 'mantz', 'manzon', 'marimÃ³n', 'marko', 'marques',
       'marr', 'marsh', 'martin', 'martini', 'mass', 'massa', 'may',
       'mayer', 'mazepin', 'mazet', 'mazzacane', 'mcalpine', 'mccarthy',
       'mccoy', 'mcdowell', 'mcgrath', 'mcguire', 'mclaren', 'mcnish',
       'mcrae', 'mcwithey', 'menditeguy', 'merhi', 'merzario', 'mieres',
       'migault', 'miles', 'milhoux', 'miller', 'mitter', 'modena',
       'monarch', 'montagny', 'monteiro', 'montermini', 'monteverdi',
       'montgomerie-charrington', 'morbidelli', 'moreno', 'morgan',
       'moser', 'moss', 'munaron', 'murray', 'musso', 'nakajima',
       'nakano', 'nalon', 'nannini', 'naspetti', 'nasr', 'natili',
       'naylor', 'nazaruk', 'needell', 'nelleman', 'nicholson', 'niday',
       'niedermayr', 'niemann', 'nilsson', 'noda', 'norris', 'nuckey',
       'nÃ¨ve', "o'brien", "o'connor", 'ocon', 'oliver', 'ongais', 'owen',
       'pablo montoya', 'pace', 'pagani', 'paletti', 'palm', 'palmer',
       'panis', 'pantano', 'papis', 'parkes', 'parnell', 'parsons',
       'patrese', 'pease', 'penske', 'perdisa', 'perkins', 'pescarolo',
       'pesenti-rossi', 'peters', 'peterson', 'petrov', 'pic', 'picard',
       'pieterse', 'pietsch', 'pilette', 'piotti', 'piper', 'piquet',
       'piquet jr.', 'pirocchi', 'pironi', 'pirro', 'pizzonia', 'piÃ¡n',
       'pollet', 'pon', 'poore', 'posey', 'pozzi', 'pretorius', 'prinoth',
       'prophet', 'prost', 'pryce', 'purley', 'puzey', 'pÃ©rez',
       'pÃ©rez-sala', 'quester', 'raby', 'rahal', 'raphanel', 'rathmann',
       'ratzenberger', 'rebaque', 'redman', 'reece', 'reed', 'rees',
       'regazzoni', 'reutemann', 'reventlow', 'revson', 'rhodes',
       'ribeiro', 'ricciardo', 'richardson', 'riess', 'rigsby', 'rindt',
       'riseley-prichard', 'robarts', 'rodrÃ­guez', 'rol', 'rollinson',
       'rolt', 'roos', 'rosberg', 'rose', 'rosier', 'rosset', 'rossi',
       'rothengatter', 'ruby', 'russell', 'russo', 'ruttman', 'ryan',
       'rÃ¤ikkÃ¶nen', 'sachs', 'said', 'sainz', 'salazar', 'salo',
       'salvadori', 'sanesi', 'sarrazin', 'sato', 'scarborough',
       'scarfiotti', 'scarlatti', 'scheckter', 'schell', 'schenken',
       'scherrer', 'schiattarella', 'schiller', 'schindler', 'schlesser',
       'schneider', 'schoeller', 'schroeder', 'schumacher', 'schuppan',
       'scott', 'scott brown', 'scotti', 'seidel', 'seiffert', 'senna',
       'serafini', 'serra', 'serrurier', 'servoz-gavin', 'settember',
       'sharp', 'shawe taylor', 'shelby', 'shelly', 'siffert', 'simon',
       'sirotkin', 'slotemaker', 'solana', 'soler-roig', 'sommer',
       'sospiri', 'south', 'sparken', 'speed', 'spence', 'stacey',
       'starrabba', 'stevens', 'stevenson', 'stewart', 'stohr',
       'stommelen', 'streiff', 'stroll', 'stuck', 'stuppacher',
       'sullivan', 'surer', 'surtees', 'sutcliffe', 'sutil', 'sutton',
       'suzuki', 'swaters', 'sweikert', 'takagi', 'takahara', 'takahashi',
       'tambay', 'taramazzo', 'tarquini', 'taruffi', 'taylor', 'teague',
       'templeman', 'testut', 'thackwell', 'thiele', 'thompson',
       'thomson', 'thorne', 'tingelstad', 'tingle', 'titterington',
       'tolan', 'trimmer', 'trintignant', 'trulli', 'tsunoda', 'tuero',
       'tunmer', 'turner', 'ulmen', 'unser', 'uria', 'vaccarella',
       'van de poele', 'van der garde', 'van der lof', 'van der vyver',
       'van lennep', 'van rooyen', 'vandoorne', 'veith', 'vergne',
       'verstappen', 'vettel', 'villeneuve', 'villeneuve sr.',
       'villoresi', 'volonterio', 'von opel', 'von stuck', 'von trips',
       'vonlanthen', 'vukovich', 'wacker', 'walker', 'wallard', 'walter',
       'ward', 'warwick', 'watson', 'webb', 'webber', 'wehrlein',
       'weidler', 'weiler', 'wendlinger', 'westbury', 'weyant', 'wharton',
       'whiteaway', 'whitehead', 'whitehouse', 'widdows', 'wietzes',
       'wilds', 'williams', 'williamson', 'wilson', 'winkelhock',
       'wisell', 'wunderink', 'wurz', 'yamamoto', 'yoong', 'zanardi',
       'zapico', 'zonta', 'zorzi', 'zunino', 'Ã©tancelin'], dtype=object)

In [522]:
rep = {'Ã£':'a','Ã¡':'a','Ã©':'e','Ã­':'i','Ã³':'o','Ã´':'o','Ãº':'u','`a':'a','Ã¨':'e','Ã¬':'i','Ã²':'o','Ã¹':'u','Ã§':'c','Ã±':'n','Å¡':'s','Ã˜':'','Ã¸':'',}

datos['surname'] =datos['surname'].replace(rep, regex=True)

In [523]:
datos_decode= datos["surname"].apply(remove_accents)

In [524]:
datos["surname"]=datos_decode.str.decode('utf8', errors='strict')

In [525]:
datos["surname"]=datos["surname"].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [526]:
datos.head()

,driverId,driverRef,number,code,dob,nationality,url,forename,surname
0,1,hamilton,44,ham,1985-01-07,british,http://en.wikipedia.org/wiki/Lewis_Hamilton,lewis,hamilton
1,2,heidfeld,\N,hei,1977-05-10,german,http://en.wikipedia.org/wiki/Nick_Heidfeld,nick,heidfeld
2,3,rosberg,6,ros,1985-06-27,german,http://en.wikipedia.org/wiki/Nico_Rosberg,nico,rosberg
3,4,alonso,14,alo,1981-07-29,spanish,http://en.wikipedia.org/wiki/Fernando_Alonso,fernando,alonso
4,5,kovalainen,\N,kov,1981-10-19,finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen,heikki,kovalainen

In [528]:
datos.to_csv('drivers_.csv', encoding='utf-8', index=False)

In [529]:
datos_df=pd.read_csv(r'C:\Users\ROXI\OneDrive\Escritorio\Proyecto Individual 1- Data 03- Soy Henry\Proyecto-Individual-1\Datasets\pandas\dataset_procesados\drivers_.csv',encoding='utf-8-sig')

In [530]:
#convert to lower case
datos['url'] = datos['url'].str.lower()
# remove trailing white spaces
datos['url'] = datos['url'].str.strip()

In [531]:
sort_forename=datos_df['number'].sort_values()
sort_forename.unique()

array(['10', '11', '12', '13', '14', '16', '17', '18', '19', '2', '20',
       '21', '22', '23', '25', '26', '27', '28', '3', '30', '31', '33',
       '35', '4', '44', '45', '5', '51', '53', '55', '6', '63', '7', '77',
       '8', '88', '89', '9', '94', '98', '99', '\\N'], dtype=object)

In [532]:
import numpy as np

In [533]:
datos_df['number']=datos_df['number'].replace('\\N',np.nan)

In [534]:
datos_df.to_csv('drivers_.csv', encoding='utf-8', index=False)

In [535]:
datos_df=pd.read_csv(r'C:\Users\ROXI\OneDrive\Escritorio\Proyecto Individual 1- Data 03- Soy Henry\Proyecto-Individual-1\Datasets\pandas\dataset_procesados\drivers_.csv',encoding='utf-8-sig')

In [537]:
datos_df

,driverId,driverRef,number,code,dob,nationality,url,forename,surname
0,1,hamilton,44.0,ham,1985-01-07,british,http://en.wikipedia.org/wiki/Lewis_Hamilton,lewis,hamilton
1,2,heidfeld,NaN,hei,1977-05-10,german,http://en.wikipedia.org/wiki/Nick_Heidfeld,nick,heidfeld
2,3,rosberg,6.0,ros,1985-06-27,german,http://en.wikipedia.org/wiki/Nico_Rosberg,nico,rosberg
3,4,alonso,14.0,alo,1981-07-29,spanish,http://en.wikipedia.org/wiki/Fernando_Alonso,fernando,alonso
4,5,kovalainen,NaN,kov,1981-10-19,finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen,heikki,kovalainen
...,...,...,...,...,...,...,...,...,...
848,850,pietro_fittipaldi,51.0,fit,1996-06-25,brazilian,http://en.wikipedia.org/wiki/Pietro_Fittipaldi,pietro,fittipaldi
849,851,aitken,89.0,ait,1995-09-23,british,http://en.wikipedia.org/wiki/Jack_Aitken,jack,aitken
850,852,tsunoda,NaN,tsu,2000-05-11,japanese,http://en.wikipedia.org/wiki/Yuki_Tsunoda,yuki,tsunoda
851,853,mazepin,NaN,maz,1999-03-02,russian,http://en.wikipedia.org/wiki/Nikita_Mazepin,nikita,mazepin
852,854,mick_schumacher,NaN,sch,1999-03-22,german,http://en.wikipedia.org/wiki/Mick_Schumacher,mick,schumacher

american, british

In [570]:
pilotos=datos_df[(datos_df['nationality'] == "american") | (datos_df['nationality'] == "british")]

In [568]:
conductor_american_british=pilotos["driverId"].values

In [569]:
conductor_american_british

array([  1,  14,  18,  19,  26,  51,  56,  65,  66,  71,  84,  87,  95,
       118, 121, 135, 141, 151, 156, 158, 174, 186, 187, 193, 205, 207,
       209, 211, 214, 226, 227, 231, 239, 240, 242, 245, 249, 252, 259,
       262, 264, 265, 270, 276, 282, 283, 288, 289, 294, 301, 302, 305,
       308, 309, 312, 320, 321, 322, 328, 329, 332, 335, 341, 342, 344,
       350, 353, 354, 357, 361, 364, 366, 367, 370, 373, 374, 378, 381,
       383, 386, 387, 388, 390, 391, 392, 393, 395, 396, 397, 398, 399,
       400, 401, 403, 404, 405, 407, 418, 419, 420, 421, 422, 433, 434,
       436, 437, 438, 440, 441, 449, 451, 452, 453, 456, 459, 460, 462,
       463, 465, 468, 469, 470, 475, 477, 479, 481, 484, 486, 490, 494,
       495, 501, 502, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514,
       515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527,
       528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540,
       541, 542, 545, 546, 547, 548, 549, 555, 556, 557, 558, 559, 560,
       561, 562, 563, 564, 565, 566, 569, 570, 571, 572, 574, 575, 576,
       578, 581, 584, 585, 587, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 601, 605, 610, 611, 612, 613, 614, 615, 616, 617, 618,
       619, 628, 629, 630, 631, 635, 636, 637, 651, 652, 653, 654, 655,
       656, 657, 658, 659, 661, 663, 664, 665, 666, 667, 673, 674, 675,
       676, 677, 678, 679, 680, 682, 683, 684, 685, 686, 687, 688, 689,
       690, 693, 696, 699, 700, 701, 702, 705, 706, 707, 708, 725, 726,
       727, 728, 729, 730, 731, 732, 733, 734, 737, 739, 742, 743, 744,
       745, 747, 749, 766, 767, 768, 769, 770, 771, 772, 777, 778, 779,
       781, 784, 785, 787, 788, 790, 794, 795, 796, 797, 798, 799, 803,
       804, 805, 814, 820, 829, 834, 835, 846, 847, 851], dtype=int64)

- Piloto con mayor cantidad de puntos en total, cuyo constructor sea de nacionalidad sea American o British