In [2]:
import pandas as pd

ruta_archivo_json = 'C:\\Users\\ROXI\\OneDrive\\Escritorio\\henry\\pi\\PI01_DATA03\\Datasets\\pit_stops.json'
datos = pd.read_json(ruta_archivo_json, orient='records')
datos

      raceId  driverId  stop  lap      time duration  milliseconds
0        841       153     1    1  17:05:23   26.898         26898
1        841        30     1    1  17:05:52   25.021         25021
2        841        17     1   11  17:20:48   23.426         23426
3        841         4     1   12  17:22:34   23.251         23251
4        841        13     1   13  17:24:10   23.842         23842
...      ...       ...   ...  ...       ...      ...           ...
8025    1047        20     1   35  18:17:15    22.04         22040
8026    1047       849     2   35  18:17:41   22.384         22384
8027    1047       817     1   39  18:23:37   22.123         22123
8028    1047       825     2   47  18:39:11   23.098         23098
8029    1047       850     3   48  18:41:11   23.217         23217

[8030 rows x 7 columns]